services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      # You will set these environment variables in the Render dashboard
      - SERPER_API_KEY=${SERPER_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARCADE_API_KEY=${ARCADE_API_KEY}
      - ARCADE_USER_ID=${ARCADE_USER_ID}

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
