# This file orchestrates the building and running of your frontend and backend services.
services:
  # The Python/FastAPI backend service
  backend:
    # Tells Docker to build an image from the './backend' directory
    build: ./backend
    ports:
      # Maps port 8000 on your computer to port 8000 inside the container
      - "8000:8000"
    environment:
      # These variables will be loaded from your .env file into the container
      - SERPER_API_KEY=${SERPER_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARCADE_API_KEY=${ARCADE_API_KEY}
      - ARCADE_USER_ID=${ARCADE_USER_ID}

  # The React frontend service
  frontend:
    # Tells Docker to build an image from the './frontend' directory
    build: ./frontend
    ports:
      # Maps port 5173 on your computer to port 80 inside the container (where Nginx runs)
      - "5173:5173"
    # This ensures the backend starts up before the frontend
    depends_on:
      - backend

